
version: '3'

services:
  web:
    build: .
    environment:
    - COVERAGE=true
    - DATABASE_URL=postgres://root:secret@db/todo-test
    depends_on:
    - db

  db:
    image: postgres
    environment:
    - POSTGRES_DB=todo-test
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=secret
